### ISSUE TITLE
Unable to include <react/bridging/Bridging.h>

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-windows#13999]
https://github.com/microsoft/react-native-windows/discussions/13985

**Comment by chrisglein** [comment]
Previously there had been issues with compilation of this particular area with MSVC vs. Clang. But we believe that has been resolved (and in fact the file has a patch override) and is used in the integration tests.
Should be a trivial change to add the header to the nuget project.

**Comment by hsjoberg** [comment]
>  Should be a trivial change to add the header to the nuget project.

I found that the files are included in the ReactCommon project 
https://github.com/microsoft/react-native-windows/blob/938daf0678f5179485f0d8a4244b50438eada9df/vnext/ReactCommon/ReactCommon.vcxproj#L182-L186

However, adding Bridging.h here does not seem to make any difference. It still cannot find the header.
Is this due to pre-built binaries being used (#13338)? If so, how can I disable this for testing purposes?

**Comment by hsjoberg** [comment]
Okay, the reason why the JSI integration tests are able to use the bridging files is because its vcxproj is importing `React.Cpp.props`, which includes bridging and related JSI folders (https://github.com/microsoft/react-native-windows/blob/2d36fbbd20219cbdadd7771ebbb1d215a8f60a33/vnext/PropertySheets/React.Cpp.props).

Whereas the vcxproj created by cpp-app/cpp-lib is importing `External\Microsoft.ReactNative.Composition.CppApp.props`, which does not (https://github.com/microsoft/react-native-windows/blob/2d36fbbd20219cbdadd7771ebbb1d215a8f60a33/vnext/PropertySheets/External/Microsoft.ReactNative.Composition.CppApp.props).
Although it's not clear to me yet where the <AdditionalIncludeDirectories> is best placed.

**Comment by jonthysell** [comment]
Removing good first issue: this will require seeing if/where we should be including these headers for external projects to consume, which may involve updating the Cxx project and header copying script.
